disable github changelog

diff --git a/niv-updater b/niv-updater
--- a/niv-updater
+++ b/niv-updater
@@ -328,24 +328,24 @@ createPullRequestsOnUpdate() {
         printf '%s%s' "$INPUT_MESSAGE_PREFIX" "${INPUT_MESSAGE_PREFIX:+$'\n'}" >>"$message"
 
         # get a short changelog if we're on github
-        if [[ -z $is_github ]]; then
-            # pretty sure this is not github
-            echo "Dependency '$dep' isn't hosted on github.com, cannot fetch the changelog" >>"$message"
-        else
-            echo "Dependency '$dep' is hosted on github.com"
+        #if [[ -z $is_github ]]; then
+        #    # pretty sure this is not github
+        #    echo "Dependency '$dep' isn't hosted on github.com, cannot fetch the changelog" >>"$message"
+        #else
+        #    echo "Dependency '$dep' is hosted on github.com"
 
-            {
-                niv_branch="$(jq -jr ".\"$dep\".branch // empty" <"$wdir/$SOURCES_JSON")"
-                printf '## Changelog for %s:\n' "$dep"
-                printf 'Branch: %s\n' "$niv_branch"
-                printf 'Commits: [%s/%s@%.8s...%.8s](https://github.com/%s/%s/compare/%s...%s)\n\n' "$dep_owner" "$dep_repo" "$revision" "$new_revision" "$dep_owner" "$dep_repo" "$revision" "$new_revision"
-                {
-                    hub api "/repos/$dep_owner/$dep_repo/compare/${revision}...${new_revision}" || true
-                } | jq -r '.commits[] '"$merges_filter"' | "* [`\(.sha[0:8])`](\(.html_url)) \(.commit.message | split("\n") | first)"' \
-                    | formatIssueLinks "$dep_owner" "$dep_repo" \
-                    | formatMentions
-            } >>"$message"
-        fi
+        #    {
+        #        niv_branch="$(jq -jr ".\"$dep\".branch // empty" <"$wdir/$SOURCES_JSON")"
+        #        printf '## Changelog for %s:\n' "$dep"
+        #        printf 'Branch: %s\n' "$niv_branch"
+        #        printf 'Commits: [%s/%s@%.8s...%.8s](https://github.com/%s/%s/compare/%s...%s)\n\n' "$dep_owner" "$dep_repo" "$revision" "$new_revision" "$dep_owner" "$dep_repo" "$revision" "$new_revision"
+        #        {
+        #            hub api "/repos/$dep_owner/$dep_repo/compare/${revision}...${new_revision}" || true
+        #        } | jq -r '.commits[] '"$merges_filter"' | "* [`\(.sha[0:8])`](\(.html_url)) \(.commit.message | split("\n") | first)"' \
+        #            | formatIssueLinks "$dep_owner" "$dep_repo" \
+        #            | formatMentions
+        #    } >>"$message"
+        #fi
 
         # print with a new line appended, as yaml swallows those
         printf '%s%s' "$INPUT_MESSAGE_SUFFIX" "${INPUT_MESSAGE_SUFFIX:+$'\n'}" >>"$message"
